spring:
  datasource:
    username: admin
    password: LucidAN21&
    url: jdbc:mysql://scc.cxnse0qgwvdu.eu-west-1.rds.amazonaws.com:3306/resource
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    url: jdbc:mysql://scc.cxnse0qgwvdu.eu-west-1.rds.amazonaws.com:3306
    schemas: resource
    user: admin
    password: TESTING
    enabled: true
keycloak:
  auth-server-url: http://ec2-34-242-16-133.eu-west-1.compute.amazonaws.com:8083/auth
  realm: SecondClosetClub
  resource: frontEnd
  public-client: true
  ssl-required: none